### ISSUE TITLE
Requesting releases

### ISSUE THREAD

**Issue by detiber** [jmhodges/bazel_gomock#20]
It would be great if this project had releases. We are using this for rebuilding mocks with Bazel in https://github.com/kubernetes-sigs/cluster-api-provider-aws and recently hit the Bazel 0.27 issue that #19 is attempting to address.

I would love it if we could watch this repo for releases and use that to track when to update our WORKSPACE file.

**Comment by justaugustus** [comment]
Hey @jmhodges, any thoughts on this?

**Comment by jmhodges** [comment]
Oh, some releases had been made, but I hadn't updated this ticket.

The latest is v1.1 https://github.com/jmhodges/bazel_gomock/releases/tag/v1.1

**Comment by justaugustus** [comment]
Thanks @jmhodges!
