### ISSUE TITLE
Gazelle puts output into go_library srcs

### ISSUE THREAD

**Issue by Globegitter** [jmhodges/bazel_gomock#5]
First of all thanks for creating this library - it has been really useful. One thing I have noticed though, is that if I have a `BUILD` file like this (as per example):

```
go_library(
    name = "go_default_library",
    srcs = [
        "client.go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//some:deps",
    ],
)

gomock(
    name = "mock_client",
    out = "mock_client.go",
    interfaces = ["MyClient"],
    library = "//some:go_default_library",
    package = "client",
)

go_test(
    name = "go_default_test",
    srcs = [
        "client_test.go",
        "mock_client.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//some:deps",
    ],
)
```

and then I run `bazel run //:gazelle` it remove `mock_client.go` from the `go_test` rule and put it into the `go_library` rule instead. Is that something you have noticed as well? Any workaround you are aware off or should I just open a ticket in rules_go?

**Comment by jmhodges** [comment]
Yeah, the trick is to end the file name with “_test.go”

**Comment by Globegitter** [comment]
Ah yes that did the trick, thanks

**Comment by Globegitter** [comment]
@jmhodges Actually just thinking a bit further about this, I wonder if the `testonly  = True` attribute should be respected for this. I actually think that would be the nicest. But I suppose there is nothing `gomock` could do about this, is there?

**Comment by jmhodges** [comment]
Yeah, don’t really have control over the right bits. Thank you!

**Comment by jmhodges** [comment]
(I updated the README with some of this stuff btw)
