### ISSUE TITLE
Should this repository be archived?

### ISSUE THREAD

**Issue by ewhauser** [jmhodges/bazel_gomock#65]
`rules_go` now has support for `gomock` - https://github.com/bazelbuild/rules_go/blob/master/extras/gomock.bzl. Should anyone be using this repository anymore?

**Comment by jmhodges** [comment]
Nope, folks shouldn't be. There's a deprecation notice in the README now, and, yep, I'm going to archive this project.

**Comment by jmhodges** [comment]
Oh, I'd hoped to [see docs show up](https://github.com/bazelbuild/rules_go/issues/3721) before archiving this repo.
